name: Build, push and deploy til prod-gcp
on: 
  push:
    paths:
      - 'kafka/team-oebs-kafka-manager-prod.yaml'
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy docker image to prod
    steps:
      - uses: actions/checkout@v4
        with:
          path: deploy
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/kafka/team-oebs-kafka-manager-prod.yaml