name: Build, push and deploy til dev-fss
on: 
  push:
    paths:
      - 'deploy/kafka/team-oebs-kafka-manager-t1.yaml'
      - 'deploy/kafka/team-oebs-kafka-manager-q1.yaml'
      - 'deploy/kafka/team-oebs-kafka-manager-u1.yaml'
  workflow_dispatch:

jobs:
  deploy-t1:
    runs-on: ubuntu-latest
    name: Deploy docker image to dev
    steps:
      - uses: actions/checkout@v4
        with:
          path: deploy
      - name: Deploy kafka-manager-t1 to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/kafka/team-oebs-kafka-manager-t1.yaml

  deploy-q1:
    runs-on: ubuntu-latest
    name: Deploy docker image to dev
    steps:
      - uses: actions/checkout@v4
        with:
          path: deploy
      - name: Deploy kafka-manager-q1 to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/kafka/team-oebs-kafka-manager-q1.yaml

  deploy-u1:
    runs-on: ubuntu-latest
    name: Deploy docker image to dev
    steps:
      - uses: actions/checkout@v4
        with:
          path: deploy
      - name: Deploy kafka-manager-u1 to dev-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/kafka/team-oebs-kafka-manager-u1.yaml