name: Build, push and deploy til prod-fss
on: 
  push:
    paths:
      - 'deploy/kafka/team-oebs-kafka-manager-prod.yaml'
  workflow_dispatch:
  
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy docker image to prod
    steps:
      - uses: actions/checkout@v4
        with:
          path: deploy
      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: deploy/.nais/prod.yaml